services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0 -p 5000
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 9876:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    build: ./services/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./services/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=login
      - POSTGRES_DB=base_db

volumes:
  postgres_data:
